service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10  
  region: eu-west-1 # Overwrite the default region used. Default is us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  hello2:
    handler: test.hello
    events:
      - http:
          method: get
          path: hello
